// Mock initial roles data
export const initialRoles = [
  {
    id: "1",
    name: "System Administrator",
    description: "Full system access and control",
    domain: "Airport",
    department: "TSA",
    category: "ASP",
    roleName: "Administrator",
    roleDescription: "Full system access and control",
    effectiveDate: "2023-01-01",
    permissions: {
      "in-review": "admin_access",
      "reference-document-access": "view_access",
      "notify-in-review": "admin_access",
      "reference-document": "view_access",
      approved: "view_access",
      deactivated: "admin_access",
      "review-administration-access": "admin_access",
      upload: "admin_access",
      "upload-working-copy": "admin_access",
      "upload-reference-document": "admin_access",
      "sign-off": "admin_access",
      "review-management": "admin_access",
      "document-view": "admin_access",
      pending: "admin_access",
      "approved-view": "admin_access",
      "final-copy": "view_access",
      summary: "view_access",
      "annotated-docs": "view_access",
      "deactivated-view": "view_access",
      "reference-documents": "view_access",
      group: "admin_access",
      "group-level": "admin_access",
      review: "view_access",
      "write-approval": "write_access",
      user: "admin_access",
      "user-level": "admin_access",
      "user-approval-level": "admin_access", 
      "user-review": "view_access",
      "user-write-approval": "write_access",
      "escalated-tasks-access": "admin_access",
      notify: "admin_access",
      assign: "admin_access",
    },
  },
  {
    id: "2",
    name: "Content Editor",
    description: "Content management and editing permissions",
    domain: "Airline",
    department: "Airline Security",
    category: "ADFP",
    roleName: "HR Manager",
    roleDescription: "Manage HR functions and employee records",
    effectiveDate: "2023-01-15",
    permissions: {
      "in-review": "write_access",
      "reference-document-access": "no_access",
      "notify-in-review": "no_access",
      "reference-document": "view_access",
      approved: "view_access",
      deactivated: "view_access",
      "review-administration-access": "admin_access",
      upload: "write_access",
      "upload-working-copy": "write_access",
      "upload-reference-document": "view_access",
      "sign-off": "no_access",
      "review-management": "admin_access",
      "document-view": "admin_access",
      pending: "admin_access",
      "approved-view": "admin_access",
      "final-copy": "view_access",
      summary: "view_access",
      "annotated-docs": "view_access",
      "deactivated-view": "view_access",
      "reference-documents": "view_access",
      group: "view_access",
      "group-level": "view_access",
      review: "view_access",
      "write-approval": "no_access",
      user: "view_access",
      "user-level": "view_access",
      "user-approval-level": "view_access",
      "user-review": "view_access", 
      "user-write-approval": "no_access",
      "escalated-tasks-access": "no_access",
      notify: "no_access",
      assign: "no_access",
    },
  },
];

// Domain and department options
export const domains = ["Airport", "Airline"];

export const departmentOptions = {
  Airport: [
    "TSA",
    "FAA",
    "Airport Security",
    "Airport Operations",
    "Public Safety",
  ],
  Airline: ["Airline Security", "Airline Operations"],
};