// Define all permissions
export const permissions = [
  // Document Repository
  {
    id: "in-review",
    title: "In Review",
    description: "Allow viewing of documents in review",
    category: "document-repository",
    section: "document-repository",
    defaultLevel: "view_access",
  },
  {
    id: "reference-document-access",
    title: "Reference Document Access",
    description: "Allow access to reference documents in review",
    category: "document-repository",
    section: "document-repository",
    allowedLevels: ["admin_access", "no_access"],
    isSubItem: true,
    subItemOf: "in-review",
    defaultLevel: "no_access",
  },
  {
    id: "notify-in-review",
    title: "Notify",
    description: "Allow notifications for documents in review",
    category: "document-repository",
    section: "document-repository",
    allowedLevels: ["admin_access", "no_access"],
    isSubItem: true,
    subItemOf: "in-review",
  },
  {
    id: "reference-document",
    title: "Reference Document",
    description: "Allow viewing of reference documents",
    category: "document-repository",
    section: "document-repository",
    allowedLevels: ["view_access", "no_access"],
    defaultLevel: "view_access",
  },
  {
    id: "approved",
    title: "Approved",
    description: "Allow viewing of approved documents",
    category: "document-repository",
    section: "document-repository",
    allowedLevels: ["view_access", "no_access"],
    defaultLevel: "view_access",
  },
  {
    id: "deactivated",
    title: "Deactivated",
    description: "Allow viewing of deactivated documents",
    category: "document-repository",
    section: "document-repository",
    allowedLevels: ["view_access", "no_access"],
  },

  // Review Administration
  {
    id: "review-administration-access",
    title: "Review Administration Access",
    description: "Top-level access to review administration",
    category: "review-administration",
    section: "review-administration",
    allowedLevels: ["admin_access", "no_access"],
  },
  {
    id: "upload",
    title: "Upload",
    description: "Allow uploading of documents",
    category: "review-administration",
    section: "review-administration",
    isSubItem: true,
    subItemOf: "review-administration-access",
    allowedLevels: ["admin_access", "write_access", "no_access"],
  },
  {
    id: "upload-working-copy",
    title: "Upload Working Copy",
    description: "Allow uploading of working copy documents",
    category: "review-administration",
    section: "review-administration",
    isSubItem: true,
    subItemOf: "upload",
    allowedLevels: ["admin_access", "write_access", "no_access"],
  },
  {
    id: "upload-reference-document",
    title: "Upload Reference Document",
    description: "Allow uploading of reference documents",
    category: "review-administration",
    section: "review-administration",
    isSubItem: true,
    subItemOf: "upload",
    allowedLevels: ["admin_access", "write_access", "no_access"],
  },
  {
    id: "sign-off",
    title: "Sign-off",
    description: "Allow signing off on documents",
    category: "review-administration",
    section: "review-administration",
    isSubItem: true,
    subItemOf: "review-administration-access",
    allowedLevels: ["admin_access", "no_access"],
  },
  {
    id: "review-management",
    title: "Review Management",
    description: "Document review management permissions",
    category: "review-administration",
    section: "review-administration",
    allowedLevels: ["admin_access", "no_access"],
  },
  {
    id: "document-view",
    title: "Admin Document Repository View",
    description: "Admin document repository viewing permissions",
    category: "review-administration",
    section: "review-administration",
    allowedLevels: ["admin_access", "no_access"],
  },
  {
    id: "pending",
    title: "Pending",
    description: "Allow viewing of pending documents",
    category: "review-administration",
    section: "review-administration",
    isSubItem: true,
    subItemOf: "document-view",
    allowedLevels: ["admin_access", "no_access"],
  },
  {
    id: "approved-view",
    title: "Approved",
    description: "Allow viewing of approved documents",
    category: "review-administration",
    section: "review-administration",
    isSubItem: true,
    subItemOf: "document-view",
    allowedLevels: ["admin_access", "view_access", "no_access"],
  },
  {
    id: "final-copy",
    title: "Final Copy",
    description: "Allow viewing of final copy documents",
    category: "review-administration",
    section: "review-administration",
    isSubItem: true,
    subItemOf: "approved-view",
    allowedLevels: ["view_access", "no_access"],
  },
  {
    id: "summary",
    title: "Summary",
    description: "Allow viewing of summary documents",
    category: "review-administration",
    section: "review-administration",
    isSubItem: true,
    subItemOf: "approved-view",
    allowedLevels: ["view_access", "no_access"],
  },
  {
    id: "annotated-docs",
    title: "Annotated Docs",
    description: "Allow viewing of annotated documents",
    category: "review-administration",
    section: "review-administration",
    isSubItem: true,
    subItemOf: "approved-view",
    allowedLevels: ["view_access", "no_access"],
  },
  {
    id: "deactivated-view",
    title: "Deactivated",
    description: "Allow viewing of deactivated documents",
    category: "review-administration",
    section: "review-administration",
    isSubItem: true,
    subItemOf: "document-view",
    allowedLevels: ["view_access", "no_access"],
  },
  {
    id: "reference-documents",
    title: "Reference Documents",
    description: "Allow viewing of reference documents",
    category: "review-administration",
    section: "review-administration",
    isSubItem: true,
    subItemOf: "document-view",
    allowedLevels: ["view_access", "no_access"],
  },

  // Tasks
  {
    id: "group",
    title: "Group",
    description: "Allow management of groups",
    category: "tasks",
    section: "tasks",
    defaultLevel : "write_access"
  },
  {
    id: "group-level",
    title: "Review  ",
    description: "Review permissions",
    category: "tasks",
    section: "tasks",
    isSubItem: true,
    subItemOf: "group",
    defaultLevel : "write_access"
  },
  {
    id: "approval-level",
    title: "Approval",
    description: "Approval permissions",
    category: "tasks",
    section: "tasks",
    isSubItem: true,
    subItemOf: "group",
    defaultLevel : "write_access"
  },
  {
    id: "review",
    title: "Review",
    description: "Allow reviewing of tasks",
    category: "tasks",
    section: "tasks",
    isSubItem: true,
    subItemOf: "group-level",
    allowedLevels: ["no_access"],
  },
  {
    id: "write-approval",
    title: "Write Approval",
    description: "Allow writing approvals for tasks",
    category: "tasks",
    section: "tasks",
    isSubItem: true,
    subItemOf: "group-level",
    allowedLevels: ["write_access", "no_access"],
  },
  {
    id: "user",
    title: "User",
    description: "Allow management of users",
    category: "tasks",
    section: "tasks",
    defaultLevel: "write_access",
  },
  {
    id: "user-level",
    title: "Review",
    description: "User review permissions",
    category: "tasks",
    section: "tasks",
    isSubItem: true,
    subItemOf: "user",
    defaultLevel : "write_access"
  },
  {
    id: "user-approval-level",
    title: "Approval",
    description: "User approval permissions", 
    category: "tasks",
    section: "tasks",
    isSubItem: true,
    subItemOf: "user",
    defaultLevel : "write_access"
  },
  {
    id: "user-review",
    title: "Review",
    description: "Allow reviewing of user tasks",
    category: "tasks",
    section: "tasks",
    isSubItem: true,
    subItemOf: "user-level",
    allowedLevels: ["no_access"],
  },
  {
    id: "user-write-approval",
    title: "Write Approval", 
    description: "Allow writing approvals for user tasks",
    category: "tasks",
    section: "tasks",
    isSubItem: true,
    subItemOf: "user-level",
    allowedLevels: ["write_access", "no_access"],
  },

  // Escalated Tasks
  {
    id: "escalated-tasks-access",
    title: "Escalated Tasks Access",
    description: "Top-level access to escalated tasks",
    category: "escalated-tasks",
    section: "escalated-tasks",
    allowedLevels: ["admin_access", "no_access"],
  },
  {
    id: "notify",
    title: "Notify",
    description: "Allow sending notifications",
    category: "escalated-tasks",
    section: "escalated-tasks",
    isSubItem: true,
    subItemOf: "escalated-tasks-access",
    allowedLevels: ["admin_access", "no_access"],
  },
  {
    id: "assign",
    title: "Assign",
    description: "Allow assigning tasks",
    category: "escalated-tasks",
    section: "escalated-tasks",
    isSubItem: true,
    subItemOf: "escalated-tasks-access",
    allowedLevels: ["admin_access", "no_access"],
  },

  // RFI (Request for Information)
  {
    id: "rfi-access",
    title: "RFI Access",
    description: "Access to Request for Information features",
    category: "rfi",
    section: "rfi",
    allowedLevels: ["admin_access", "write_access", "view_access", "no_access"],
    defaultLevel: "view_access",
  },
  {
    id: "rfi-create",
    title: "Create R.F.I",
    description: "Allow creating new RFI requests",
    category: "rfi",
    section: "rfi",
    isSubItem: true,
    subItemOf: "rfi-access",
    allowedLevels: ["admin_access", "write_access", "view_access","no_access"],
    defaultLevel: "no_access",
  },
  {
    id: "rfi-details",
    title: "R.F.I Details",
    description: "Allow access to RFI details and information",
    category: "rfi",
    section: "rfi",
    isSubItem: true,
    subItemOf: "rfi-access",
    allowedLevels: ["admin_access", "write_access", "view_access", "no_access"],
    defaultLevel: "no_access",
  },
  {
    id: "rfi-upload-templates",
    title: "Upload Templates",
    description: "Allow uploading and managing RFI templates",
    category: "rfi",
    section: "rfi",
    isSubItem: true,
    subItemOf: "rfi-access",
    allowedLevels: ["admin_access", "write_access", "view_access", "no_access"],
    defaultLevel: "view_access",
  },
];

// Define sections with parent-child relationships
export const sections = {
  "document-repository": {
    title: "Document Repository",
    description: "Document repository permissions",
    parents: {},
  },
  "review-administration": {
    title: "Review Administration",
    description: "Review administration permissions",
    parents: {
      "review-management": {
        title: "Review Management",
        description: "Document review management permissions",
      },
      "document-view": {
        title: "Admin Document Repository View",
        description: "Document viewing permissions",
      },
    },
  },
  tasks: {
    title: "Tasks",
    description: "Task management permissions",
  },
  "escalated-tasks": {
    title: "Escalated Tasks",
    description: "Escalated task permissions",
  },
  rfi: {
    title: "RFI",
    description: "Request for Information permissions",
  },
};