export const sampleSavedGroups = [
    {
      id: "sample-group-1",
      name: "Airline Defense Maintenance",
      documentName: "AircraftMaintenance.docx",
      footerContent: "This is a footer 1",
      reviewContent: [
        {
          id: "sample-review-1",
          content: "The aircraft maintenance manual states that visual inspections of the fuselage must be performed after every 500 flight hours or 3 months, whichever comes first.",
          fileName: "",
          hasImage: false,
          fileType: null,
        },
        {
          id: "sample-review-2",
          content: "Section 4.2.3: Emergency procedures for cabin decompression include immediate deployment of oxygen masks and descent to 10,000 feet or the minimum safe altitude, whichever is higher.",
          fileName: "",
          hasImage: false,
          fileType: null,
        },
        {
          id: "sample-review-3",
          content: "According to FAA regulation §121.359, cockpit voice recorders must retain the last 2 hours of recorded information instead of the previous 30-minute requirement.",
          fileName: "",
          hasImage: false,
          fileType: null,
        },
      ],
      relatedContent: [],
    },
    {
      id: "sample-group-2",
      name: "Airport Safety and Compliance",
      documentName: "SafetyCompliance.docx",
      footerContent: "This is a footer 2",
      reviewContent: [
        {
          id: "sample-review-4",
          content: "FAA Advisory Circular 120-92B outlines the Safety Management System (SMS) framework, requiring operators to identify hazards, assess risk, and implement safety assurance practices.",
          fileName: "",
          hasImage: false,
          fileType: null,
        },
        {
          id: "sample-review-5",
          content: "ICAO Annex 6 mandates that all commercial aircraft must be equipped with a Terrain Awareness and Warning System (TAWS) to prevent controlled flight into terrain (CFIT).",
          fileName: "",
          hasImage: false,
          fileType: null,
        },
        {
          id: "sample-review-6",
          content: "Under Part 135, aircraft operators must perform weight and balance calculations prior to every flight to ensure compliance with center of gravity and structural limits.",
          fileName: "",
          hasImage: false,
          fileType: null,
        },
      ],
      relatedContent: [],
    },
  ]


export const availableDocuments = [
    { id: "doc-1", name: "Document A.docx" },
    { id: "doc-2", name: "Document B.pdf" },
    { id: "doc-3", name: "Guidelines.docx" },
    { id: "doc-4", name: "sample.docx" },
    { id: "doc-5", name: "sample-2.docx" },
    { id: "doc-6", name: "Airport.docx" },
    { id: "doc-7", name: "Mickey-mouse.docx" },
    { id: "doc-8", name: "ProjectPlan_Q1.docx" },
    { id: "doc-9", name: "TeamRoster.pdf" },
    { id: "doc-10", name: "FinancialReport2024.docx" },
    { id: "doc-11", name: "Client-Proposal.docx" },
    { id: "doc-12", name: "UserManual.pdf" },
    { id: "doc-13", name: "MeetingNotes_March.docx" },
    { id: "doc-14", name: "Invoice_1098.pdf" },
    { id: "doc-15", name: "CompanyPolicy.docx" },
    { id: "doc-16", name: "Terms_Conditions.docx" },
    { id: "doc-17", name: "PrivacyPolicy.docx" },
    { id: "doc-18", name: "Resume_JohnDoe.pdf" },
    { id: "doc-19", name: "Checklist_Tasks.docx" },
    { id: "doc-20", name: "TrainingMaterials.pdf" },
    { id: "doc-21", name: "AnnualReview.docx" },
    { id: "doc-22", name: "Budget2025.pdf" },
    { id: "doc-23", name: "PerformanceReport.docx" },
    { id: "doc-24", name: "LegalAgreement.pdf" },
    { id: "doc-25", name: "OnboardingGuide.docx" },
  ];