

export const sampleData = [
  {
    id: 1,
    title: "Annual Report 2024",
    fileType: "pdf",
    type: "Annual Report",
    status: "approved",
    category: "ASP",
    department: "TSA",
    domain: "Airport",
    finalCopy: "This is the final copy content...",
    uploadedAt: "2025-01-01 12:47:20",
    lastActionTS: "2025-01-02 14:30:15",
    workingCopy: "This is the working copy content...",
    owner: {
      officer: "Officer 1",
      department: "TSA",
      title: "Security Manager",
    },
  },
  {
    id: 2,
    title: "Security Guidelines Draft",
    fileType: "docx",
    type: "Security Manual",
    status: "pending",
    category: "ASP",
    department: "FAA",
    domain: "Airport",
    finalCopy: "This is the final copy content...",
    uploadedAt: "2025-01-01 12:47:20",
    lastActionTS: "2025-01-03 09:15:42",
    workingCopy: "This is the working copy content...",
    owner: {
      officer: "Officer 1",
      department: "FAA",
      title: "Security Manager",
    },
  },
  {
    id: 3,
    title: "Business Proposal",
    fileType: "pdf",
    type: "Business Document",
    status: "approved",
    category: "AEP",
    department: "Public Safety",
    domain: "Airline",
    finalCopy: "Proposal final content...",
    workingCopy: "Proposal draft content...",
    uploadedAt: "2025-05-02 17:47:20",
    lastActionTS: "2025-05-03 11:22:30",
    owner: {
      officer: "Officer 2",
      department: "Airport Security",
      title: "Finance Manager",
    },
  },
  {
    id: 4,
    title: "Marketing Plan Draft",
    fileType: "docx",
    type: "Marketing Plan",
    status: "pending",
    category: "AEP",
    department: "Public Safety",
    domain: "Airline",
    finalCopy: "Proposal final content...",
    uploadedAt: "2025-05-02 17:47:20",
    lastActionTS: "2025-05-04 16:45:18",
    workingCopy: "Proposal draft content...",
    owner: {
      officer: "Officer 2",
      department: "Airport Security",
      title: "Finance Manager",
    },
  },
  {
    id: 5,
    title: "TSA Security Guidelines",
    fileType: "pdf",
    type: "Reference Document",
    status: "refdoc",
    reviewStatus: "reference",
    isReference: true,
    category: "ASP",
    department: "TSA",
    domain: "Airport",
    finalCopy: "Security guidelines reference content...",
    uploadedAt: "2025-04-15 09:30:00",
    lastActionTS: "2025-04-16 13:45:25",
    owner: {
      officer: "Officer 3",
      department: "Airport Operations",
      title: "HR Director",
    },
  },
  {
    id: 6,
    title: "Aviation Safety Manual",
    fileType: "pdf",
    type: "Reference Document",
    status: "refdoc",
    reviewStatus: "reference",
    isReference: true,
    category: "SMS",
    department: "FAA",
    domain: "Airport",
    finalCopy: "Aviation safety reference content...",
    uploadedAt: "2025-03-20 14:15:00",
    lastActionTS: "2025-03-21 10:20:35",
    owner: {
      officer: "Officer 4",
      department: "FAA",
      title: "Safety Director",
    },
  },
];

export const sampleApprovalNodes = [
  {
    id: "1",
    label: "Application Security Group",
    type: "group",
    status: "Initiated",
    attributes: [
      { name: "Role", value: "ASC" },
      { name: "Department", value: "ASC" },
      { name: "Location", value: "JFK" },
      { name: "Members", value: "2" },
    ],
  },
  {
    id: "2",
    label: "Non-Application Security Group",
    type: "group",
    status: "Assigned",
    attributes: [
      { name: "Role", value: "Non-ASC" },
      { name: "Department", value: "Non-ASC" },
      { name: "Location", value: "JFK" },
      { name: "Members", value: "5" },
    ],
  },
  {
    id: "3",
    label: "TSA",
    type: "group",
    status: "Not Assigned",
    attributes: [
      { name: "Role", value: "TSA" },
      { name: "Department", value: "TSA" },
      { name: "Location", value: "JFK" },
      { name: "Members", value: "5" },
    ],
  },
  {
    id: "4",
    label: "Application Security Group",
    type: "group",
    status: "Not Assigned",
    attributes: [
      { name: "Role", value: "ASC" },
      { name: "Department", value: "ASC" },
      { name: "Location", value: "JFK" },
      { name: "Members", value: "2" },
    ],
  },
];

// Mock data for reference documents
export const mockReferenceDocuments = [
  { id: "ref1", name: "Airport Security Manual", type: "PDF" },
  { id: "ref2", name: "TSA Compliance Guidelines", type: "PDF" },
  { id: "ref3", name: "Aviation Safety Protocol", type: "DOCX" },
  { id: "ref4", name: "Emergency Response Procedures", type: "PDF" },
  { id: "ref5", name: "Aircraft Maintenance Standards", type: "PDF" },
  { id: "ref6", name: "Security Personnel Training Guide", type: "DOCX" },
  { id: "ref7", name: "Baggage Screening Protocol", type: "PDF" },
  { id: "ref8", name: "Access Control Procedures", type: "PDF" },
  { id: "ref9", name: "Incident Reporting Guidelines", type: "DOCX" },
  { id: "ref10", name: "Security Audit Checklist", type: "PDF" },
  { id: "ref11", name: "Perimeter Security Standards", type: "PDF" },
  { id: "ref12", name: "Cyber Security Framework", type: "DOCX" },
  { id: "ref13", name: "International Aviation Standards", type: "PDF" },
  { id: "ref14", name: "Risk Assessment Template", type: "PDF" },
  { id: "ref15", name: "Security Training Schedule", type: "PDF" },
];


export const sampleSummaryData = {
    title: "Document Review Summary",
    reviewContentSelected: "Sections A, B, and C",
    reviewGroups: [
      {
        id: "group1",
        title: "Initial Review Group",
        status: "Approved",
        approvedAt: "2024-01-15 14:30:00",
        comments: [
          {
            id: "comment1",
            title: "Initial Comment",
            user: "John Doe",
            timestamp: "2024-01-15 14:30:00",
            content: "This is the initial review comment.",
            replies: [
              {
                id: "reply1",
                user: "Jane Smith",
                timestamp: "2024-01-15 15:00:00",
                content: "Reply to the initial comment.",
              },
            ],
          },
        ],
      },
      {
        id: "group2",
        title: "Legal Review Group",
        status: "Approved",
        approvedAt: "2024-01-16 10:00:00",
        comments: [
          {
            id: "comment2",
            title: "Legal Comment",
            user: "Alice Johnson",
            timestamp: "2024-01-16 10:00:00",
            content: "This is the legal review comment.",
            replies: [],
          },
        ],
      },
    ],
}