// Sample data for the escalation table
export const escalations = [
  {
    id: "esc-002",
    category: "Compliance Alert",
    documentName: "Regulatory Compliance Update",
    role: "Compliance Manager",
    assignedTo: "Emma Davis",
    assignedAt: "08 Apr 2025 at 14:30:45",
    expiredAt: "15 Apr 2025 at 14:30:45",
    status: "Active",
    priority: "Medium",
    departmentId: "COMP-02",
  },
  {
    id: "esc-003",
    category: "System Outage",
    documentName: "Critical System Recovery Plan",
    role: "IT Manager",
    assignedTo: "Michael Chen",
    assignedAt: "05 Apr 2025 at 11:20:18",
    expiredAt: "12 Apr 2025 at 11:20:18",
    status: "Expired",
    priority: "Critical",
    departmentId: "IT-03",
  },
  {
    id: "esc-004",
    category: "Customer Complaint",
    documentName: "Customer Resolution Process",
    role: "Customer Service Lead",
    assignedTo: "Sophia Rodriguez",
    assignedAt: "09 Apr 2025 at 15:45:30",
    expiredAt: "16 Apr 2025 at 15:45:30",
    status: "Active",
    priority: "Low",
    departmentId: "CS-04",
  },
  {
    id: "esc-005",
    category: "Operational Risk",
    documentName: "Business Continuity Plan",
    role: "Operations Director",
    assignedTo: "Robert Johnson",
    assignedAt: "07 Apr 2025 at 10:05:12",
    expiredAt: "14 Apr 2025 at 10:05:12",
    status: "Active",
    priority: "High",
    departmentId: "OPS-05",
  },
  {
    id: "esc-006",
    category: "Security Incident",
    documentName: "Phishing Attack Response",
    role: "IT Security Specialist",
    assignedTo: "Alex Thompson",
    assignedAt: "06 Apr 2025 at 08:30:00",
    expiredAt: "13 Apr 2025 at 08:30:00",
    status: "Expired",
    priority: "Medium",
    departmentId: "SEC-06",
  },
  {
    id: "esc-007",
    category: "HR Issue",
    documentName: "Workplace Harassment Claim",
    role: "HR Director",
    assignedTo: "Jennifer Lee",
    assignedAt: "11 Apr 2025 at 13:25:40",
    expiredAt: "18 Apr 2025 at 13:25:40",
    status: "Active",
    priority: "High",
    departmentId: "HR-07",
  },
];